apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-tcp
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 13000
      targetPort: discovery-tcp
      protocol: TCP
      name: discovery-tcp
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-udp
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 12000
      targetPort: discovery-udp
      protocol: UDP
      name: discovery-udp
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}


{{- if .Values.metrics.enabled  -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-metrics-tcp
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.metrics.metricsAPIPort }}
      targetPort: metrics-tcp
      protocol: TCP
      name: metrics-tcp
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}