apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-migrations
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{ $root := . }}
{{- range $path, $_ :=  .Files.Glob  "migrations/**.sql" }}
{{- with $root }}
  {{ $path | replace "migrations/" ""}}: |-
{{ .Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
